FROM codercom/code-server:latest
RUN rm -rf /home/coder/.local/share/code-server/extensions/github.copilot* || true
RUN rm -rf /home/coder/.local/share/code-server/extensions/github.copilot-chat* || true
EXPOSE 8080

CMD ["code-server","/home/coder/Note", "--bind-addr", "0.0.0.0:8080", "--auth", "none"]